# NumPy, Numerical Computing 1

In [1]:
import numpy as np # importing the module is always a good place to start
#import psycopg2

## What is NumPy?

- Short for "Numeric Python", NumPy is a module for scientific computing in Python
- NumPy adds a multidimensional array object to the strings, lists, dictionaries etc., available in Python by default. 



NumPy provides derived objects, such as masked arrays and matrices as well as routines for operations on arrays.
Which include:

- mathematical
- logical
- shape manipulation 
- sorting 
- selecting 
- linear algebra 
- basic statistical operations
- random simulation 

and others.

- NumPy is a key factor in the current popularity of Python as a go-to language for data science applications.

## Efficient Array Computation with NumPY

Let's compare a standard Python list comprehension and NumPy arrays ro see which is more efficient.
We will multiply two sets with 10,000 elements, element by element.  
The `timeit` module is imported and the `timeit.timeit` method is used to measure the average time each method takes to complete out of 10,000 trials.

- Vectorization, which is the absence of any explicit looping, indexing, etc., in the NumPy code makes computations with arrays very efficient.    
- Removing inefficient “for loops” leaves vectorized code more concise and easier to read than standard Python notation and fewer lines of code lead to fewer bugs.  
- NumPy code is similar to standard mathematical notation and is more intuitive and readable as a result.

Let's compare a standard Python list comprehension and NumPy arrays ro see which is more efficient.
We will multiply two sets with 10,000 elements, element by element.  
The `timeit` module is imported and the `timeit.timeit` method is used to measure the average time each method takes to complete out of 10,000 trials.

In [4]:
import timeit

def list_method():
    list_a = range(10000)
    list_b = range(10000)

    list_result = [list_a[i] * list_b[i] for i in range(10000)]

print(timeit.timeit(list_method, number = 10000))

21.18474504200003


In [5]:
def array_method():
    array_a = np.arange(10000)            # the np.arange() function is similar to the range() function in standard Python and will be discussed at a later point
    array_b = np.arange(10000)

    array_result = array_a * array_b      # notice the simplified syntax
    
print(timeit.timeit(array_method, number = 10000))

0.1352406250000513


# Learning Objectives 

1. **Introduction to Arrays.** Introduce and describe NumPy arrays.      
2. **Array Creation.** Create and shape placeholder arrays.
3. **Array Basic Operations.** Carry out basic operations on arrays.   

# Learning Obejctive 1: Introduction to Arrays

#### Introduce, describe and create NumPy arrays.

## What is a NumPy array?

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

In [8]:
a = np.array([1, 0, 0, 0, 1, 0, 0, 0, 0])
print(a)
print(type(a))
print(a.dtype)

[1 0 0 0 1 0 0 0 0]
<class 'numpy.ndarray'>
int64


### Features of arrays

- The elements in a NumPy array must be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of Python objects, including NumPy, thereby allowing for arrays of different sized elements.

- NumPy arrays have a fixed size at creation. Changing the size of an ndarray creates a new array and deletes the original.

- NumPy arrays facilitate advanced mathematical and other types of operations on large datasets. 

- Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

### Why is it called ndarray?

NumPy arrays are called `ndarrays` to emphasize that they can be multi-dimensional.

Array `a` is a one-dimensional array containing only integers as its elements. 

In [13]:
a = np.array([1,2, 3, 4, 5, 6, 7, 8])    # the np.array() function is used to create an ndarray from a list
print(a)
print(a.shape)

[1 2 3 4 5 6 7 8]
(8,)


Array `b` contains one-dimensional arrays as its elements and is therefore considered a two-dimensional array. 

In [12]:
b = np.array([[1,2],[3,4],[5, 6],[7, 8]]) # the np.array() function is used to create an ndarray from a list that contains lists
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


Array `c` contains two-dimensional arrays as its elements and is therefore considered a three-dimensional array.

In [14]:
c = np.array([[[1,2],[3,4]],[[5, 6],[7, 8]]])  # the np.array() function is used to create an ndarray from a list that contains lists that also contains lists
print(c)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


The nesting of arrays, and the number of dimensions, can go on to an arbitrary number “n” which is why NumPy arrays are referred to as **n-dimensional** arrays or `ndarray`.

## Creating Arrays

NumPy arrays can be created from any Python list or tuple using the `np.array` method.  
The type of the array is deduced automatically by NumPy.

In [34]:
a = np.array([1, 2, 3, 4], dtype = 'i')                    # the input is a list of integers
print(a)              
print(a.dtype)                                # the .dtype method is used to print the data type

[1 2 3 4]
int32


In [16]:
b = np.array([1.1, 2.1, 3.1, 4.1])            # the input is a list of floats
print(b)
print(b.dtype)                                # the .dtype method is used to print the data type

[1.1 2.1 3.1 4.1]
float64


In [21]:
a = np.array([ 0.5, 1.0, 1.5, 2., 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.])
print(a)
print(a.dtype)

# trailing zeros, whether present or absesnt in the array, are absent in the printout

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]
float64


The data type of the array can be explicitly specified at creation time.  
NumPy supports a much greater variety of numerical types than Python.  
NumPy floats and integers default to double precision, int64 and float64.

In [24]:
a = np.array([1, 2, 3, 4], dtype = float)    # though the input is a list of integers the dtype argument is set to 'float'
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


In [28]:
x = np.array(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])
#x = np.array(["aaa", "bb", "cc", "dd", "ee", "ff", "gg", "hh", "ii", "jj"])
x

#< represents byte order, small end （ the least significant byte is stored in the smallest address ）
#U unicode, data type
#1 represents element bit length, data size

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [29]:
x[0]='zz' #Once an array is created the data type may impede future inputs
x

array(['z', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='<U1')

## Creating Vectors

#### What is a vector?

- A vector is a two-dimensional NumPy array with one of the two axes being equal to 1.  
- Unlike a scalar, which is a single number or magnitude, a vector is a list of numbers meant to convey magnitude and direction in an arbitrary number of dimensions.  
- Row vectors (horizontal) and column vectors (vertical), are very important for vector algebra and machine learning applications.

- In order to create a vector we use the `np.array` method being careful to use double brackets to create a two-dimensional array of shape (1, 3) for example is two-dimensional as opposed to a one-dimensional array of shape (3, ).

#### Row Vectors

In [ ]:
row_vector = np.array([[1, 2, 3]])         # creating a two-dimensional array from a list
print(row_vector)                         # note the double brackets

In [ ]:
print(row_vector.shape)                   # confiming the shape of row_vector is (1, 3)
                                          # there are three elements in lowest dimension

In [ ]:
print(np.where(row_vector == 3))           # np.where provides the indexes at a given value in the array
                                           # all the elements are at index 0 in the second dimension 

#### Column Vectors

In [ ]:
column_vector = np.array([[10],[20],[30]]) # creating a two-dimensional array from a list
print(column_vector)                       # note the double brackets

In [ ]:
print(column_vector.shape)                 # confiming the shape of column_vector is (3, 1) and not (3,)

In [ ]:
print(np.where(column_vector == 30))       # all the elements are at index 0 in the first dimension

# Check for understanding

#### Which of the following statements are true? Select all that apply.

(A): A single NumPy array can contain many data types

(B): A single NumPy array typically contains only one type of data

(C): NumPy arrays can be appended after creation and have no fixed size

(D): NumPy arrays are created with their size locked in and cannot be appended like lists

(E): Calculations across and between arrays are less efficient with NumPy than standard Python

# Learning Obejctive 2: Array Creation

#### Create and shape placeholder arrays.

## Placeholder Arrays

NumPy offers several solutions for creating arrays with initial placeholder content. These minimize the necessity of growing arrays down the line, requiring deleting and rewriting, which are expensive operations.

#### np.zeros and np.ones

`np.zeros` creates an array of zeros and `np.ones` creates an array of ones.  
The first argument plugged into the function controls the number of rows and columns in the placeholder arrays and the data type can be specified as the second argument.  
By default, the dtype of a created placeholder array is float64.  
**np.function((rows, columns), dtype = data_type)**  

In [35]:
a = np.zeros((3,))
print(a.dtype)
print(a)

float64
[0. 0. 0.]


In [48]:
b = np.ones((3,5), dtype = int)
print(b.dtype)
print(b)

int64
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### np.empty

`np.empty` creates an array of uninitialized values.  
The values that were already at that location in the memory before the operation was activated.  
This allows the array to be created very quickly but, as you can see below, the content appears random and depends on the state of the memory.

In [49]:
a = np.empty((2,3))
print(a.dtype)
print(a)

float64
[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


In [51]:
b = np.empty((2,3), dtype = int)
print(b.dtype)
print(b)

int64
[[1 1 1]
 [1 1 1]]


#### np.arange

`np.arange` is used to create sequences of integers  
This function is analogous to the Python built-in range, but returns an array.  
**np.arange(inclusive_start, exclusive_stop, step_size)**

In [57]:
a = np.arange(0,10,10)                   # np.arange can assume an array of integers from inputs
print(a.dtype)
print(a)

int64
[0]


In [58]:
b = np.arange(0.1,1.0,0.1)
print(b.dtype)
print(b)

float64
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### np.linspace

`np.linspace` can be used as an alternative to np.arange.  
The function receives the number of elements that we want as an argument instead of the step argument, allowing the user to more easily select the size of the resulting array.  
**np.linspace(inclusive_start, inclusive_stop, number_of_steps)**

In [60]:
np.linspace(1,2)  #Defaults value 50 elements
#np.linspace(2,5)  #Defaults value 50 elements

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [68]:
a = np.linspace(0,100,10)  
print(a.dtype)
print(a)

b = np.linspace(1,10,10)        # because division is at the heart of np.linspace the float datatype is assumed         
print(b.dtype)
print(b)


float64
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
float64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
import matplotlib.pyplot as plt

def plot_linspace(n):
    fig = plt.figure()
    ax = fig.add_subplot(111)                 #fig.add_subplot(221), fig.add_subplot(222), fig.add_subplot(331)    
    x = np.linspace(0, 10, n)  
    y = np.linspace(0, 10, n)                          #np.zeros(n)
    p = ax.plot(x, y, 'c',markersize=8)       #Try replacing the 'string' in the function with different letters
    ax.set_xlim([-0.5,10.5])
    plt.show()

In [ ]:
plot_linspace(20)

In [ ]:
def plot_linspace(n):
    fig = plt.figure()
    ax = fig.add_subplot(111) 
    y = np.linspace(0, 10, n)
    x = np.linspace(0, 10, n)
    p = ax.plot(x, y, 'c',markersize=8) #Try replacing the 'string' in the function with different letters
    ax.set_xlim([-0.5,10.5])
    plt.show()

In [ ]:
plot_linspace(20)

# Check for understanding

- Make the line in the above chart point at a 45° angle up and then down

## Random Arrays

Random numbers are often needed for applications in gambling, statistical sampling, computer simulation, cryptography, completely randomized design, and other areas where producing an unpredictable result is desirable. NumPy offers many convenient ways to create arrays of various shapes and populate them with random numbers.  

#### random.random

To populate an array with random samples between 0 and 1 from a uniform distribution, you can use the `random.random` function.  
**random.random(number_of_random_values)**

In [ ]:
a = (np.random.random(3)) * 100
print(a)
a.dtype

Double parentheses can be used to select a shape for the array produced in this manner.

In [ ]:
b = np.random.random((3,3,3))
print(b)

#### random.rand

To produce an array of random numbers between 0 and 1 from a **uniform** distribution, of a given shape, the `random.rand` function can be used.  
The function assumes the creation of an array and doesn’t require double parentheses when inputting the shape of the array.

In [ ]:
a = np.random.rand(2,3,3)
print(a)

#### random.randn

To produce an array of random numbers between -3 and 3 from a normal distribution of a given shape the `random.randn` function can be used.  
As the distribution is normal the numbers at the center, closer to 0, will occur more frequently than those at the extremes.  
- ~68% of values within one standard deviation from the mean  
- ~95% of values within two standard deviations from the mean  
- ~99% of values within three standard deviations from the mean  

In [ ]:
b = np.random.randn(3,2,3)
print(b)

In [ ]:
def plot_normal():
    norm = np.random.normal(loc=1.0, scale=1.0, size=1000)

    fig, ax = plt.subplots(figsize=(10, 4))
    _ = ax.hist(norm, bins=100, color="k")
    #matplotlib. colors => b : blue. g : green.r : red. c : cyan. m : magenta. y : yellow. k : black. w : white.
    
plot_normal()

#### random.randint

To produce an array of random integers within a given range the `random.randint` function is used.  
Though a one-dimensional array is produced by default a size parameter can be specified to produce an array of any desired shape.  
**randint(int1_inclusive, int2_exclusive, number of elements)**

In [ ]:
a = np.random.randint(1,10,100)
print(a)

In [ ]:
b = np.random.randint(-10,10, size=(3,3,4))
print(b)

#### random.choice

The `random.choice` function can be used to generate a random sample from a given one-dimensional array, or list.  
Like random.randint, the size parameter can be used to select the shape of the resultant array.

In [71]:
names = ['Tom', 'Dick', 'Harry', 'Jane', 'Eryn', 'Marie']

a = np.random.choice(names)
#a = np.random.choice(names, size=(3,3))
print(a)

Tom


The probability parameter, p, can be used to select the probability that a given element will be selected.  
The probability for a given element must input at the same index as the element itself in the original list or array.

In [ ]:
b = np.random.choice(names, size=(3,3), p=[0.0,0.15,0.15,0.2,0.2,0.3])
print(b)

# Breakout

Create a function called `loaded_die(numbers)` that takes in a list of numbers, 1 through 6, and produces a single number as an output, simulating a dice roll. Since this die is loaded the probability of landing a 5 or 6 is 60% while all other numbers are unaffected.

# Learning Obejctive 3: Array Basic Operations 
#### Carry out basic operations on arrays


# Basic Operations

NumPy provides many options for interacting with arrays once they are created.  
There are methods for shaping arrays to the desired size and dimensions, checking the descriptive attributes of arrays.  
There are common mathematical functions such as standard deviation and square root. 

## Shaping Arrays

The shape of an array is the number of elements in each dimension. important component of functionality, it determines and limits the arrays that it can interact with directly or through broadcasting.  
By default, when you print an array, NumPy displays it in a similar way to nested lists, with the following layout:

- the last axis is printed from left to right
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

#### ndarray.reshape

The `ndarray.reshape` function is used to select a desired shape for a given array. 
In the example, `a.reshape(x,y,z)` returns an array of a desired shape without changing the original array, “a” is the original array, “z” is the number of elements per one-dimensional array, “y” is the number of one-dimensional arrays and “x” is the number of two-dimensional arrays. Array “a” is printed at the end of the series to show that the series of transformations that were undertaken did not change the original array.

A quick check can be performed to confirm that a given shape is valid for an array. In a valid array, the product of the multiplication of the axes should equal to the number of elements in an array. For example, a one-dimensional array with 16 elements could be transformed into arrays with the shapes (4, 4) or (2, 2, 4) as 4 × 4 = 16 and 2 × 2 × 4 = 16 but not a shape such as (2, 2, 3) as 2 × 2 × 3 = 12 and would not contain the correct number of elements.

In [ ]:
a = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])  # one-dimensional array
print(a)

In [ ]:
b = a.reshape(2,6)                                     # two-dimensional array
print(b)

In [ ]:
c = b.reshape(2,2,3)                                   # three-dimensional array
print(c)

- the last axis is printed from left to right
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [ ]:
print(a)                                               # original one-dimensional array is unchanged

#### -1

NumPy provides a convenient feature for people that have difficulty figuring out the appropriate dimensions for their arrays.  
If a dimension is given as -1 in a reshaping operation, this dimension is calculated automatically. This placeholder may be used in only one dimension per reshaping operation.

In [ ]:
a = np.arange(24)
print(a)

In [ ]:
b = a.reshape(4, -1) #the number of dimensions = the number of arguments
                     # in the reshape function
print(b)

In [ ]:
c = b.reshape(3,-1,4) #3*5*2=30
print(c)

In [ ]:
print(a)

#### ndarray.resize

The ndarray.resize works and accepts arguments in a manner very similar to ndarray.reshape but unlike that operation ndarray.resize modifies the array itself and doesn’t accept –1 as a valid dimension wildcard.

In [ ]:
a = np.arange(6)
print(a)

In [ ]:
a.resize(3,2)
print(a)

In [ ]:
print(a)                      # original one-dimensional array is replaced

In [ ]:
a.resize(2,-1)                # -1 is not accepted as an argument
print(a)

## Shaping Vectors

Because vectors are two-dimensional arrays, ndarrays can be reshaped into vectors.   
A column vector is created when an array is shaped with all its elements stacked in a single column, where the number of units in each row is one, as in ndarray.reashape(10, 1) or ndarray.reashape(-1, 1).  
A row vector is created when an array is shaped with all its elements stacked in a single row, where the number of units in each column is one, as in ndarray.reashape(1, 10) or ndarray.reashape(1,- 1).  

In [ ]:
a = np.array([[1], [2], [3], [4]]).reshape(2,2)
print (a)

In [ ]:
b = a.reshape(4, 1)   # column vector
print(b)

In [ ]:
c = a.reshape(1,4)    # row vector
print(c)

## Basic Attributes

ndarray is a distinct object and has unique attributes.  
NumPy provides methods for the user to explore these attributes. Arrays a, b, and c, each shaped in a different way, will be used to demonstrate these methods.

In [ ]:
a = np.array([ 0.5, 1.0, 1.5, 2., 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.])
print(a)

In [ ]:
b = a.reshape(2,6)
print(b)

In [ ]:
c = np.arange(24).reshape(2,2,-1)
print(c)

#### ndarray.ndim

`ndarray.ndim` returns the number of dimensions of the array.

In [ ]:
print(a.ndim)

In [ ]:
print(b.ndim)

In [ ]:
print(c.ndim)

#### ndarray.shape 

`ndarray.shape` returns a tuple of integers indicating the size of the array in each dimension.  
For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

In [ ]:
print(a.shape)

In [ ]:
print(b.shape)

In [ ]:
print(c.shape)

#### ndarray.size

`ndarray.size` returns the product of the array’s dimensions. This is equal to the product of the elements of shape.

In [ ]:
print(a.shape)
print(a.size) # 12 * 1 = 12

In [ ]:
print(b.shape)
print(b.size) # 2 * 6 = 12

In [ ]:
print(c.shape)
print(c.size) # 2 * 2 * 6 = 12

#### ndarray.dtype

`ndarray.dtype` returns an object describing the type of the elements in the array.  
One can create or specify dtype’s using standard Python types. Additionally, NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

In [ ]:
print(a.dtype)

In [ ]:
print(b.dtype)

In [ ]:
print(c.dtype)
type(c)

#### ndarray.itemsize

`ndarray.itemsize` returns the size in bytes of each element of the array.  
For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8).  
It is equivalent to ndarray.dtype.itemsize.

In [ ]:
print(a.itemsize)

In [ ]:
print(b.itemsize)

In [ ]:
print(c.itemsize)

#### ndarray.data

`ndarray.data` returns the buffer containing the actual elements of the array.  
Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [ ]:
print(a.data)

In [ ]:
print(b.data)

In [ ]:
print(c.data)

## Basic Functions

Simple aggregate functions can be applied straightforwardly to one-dimensional Numpy arrays.

In [ ]:
a = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])    # one-dimensional array
print(a)

In [ ]:
print(a.sum())

In [ ]:
print(a.min())

In [ ]:
print(a.mean())

Multi-dimensional arrays come with the added functionality of per-column and per-row aggregartion.  
With the additional axis argument you can choose whether to apply the function to the rows of an array (axis = 1) or the columns (axis = 0).

In [ ]:
b = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]]) # two-dimensional array
print(b)

In [ ]:
print(b.sum(axis=1))          # returns the sum of elements in each row

In [ ]:
print(b.min(axis=0))          # returns the smallest element in each column

In [ ]:
print(b.max(axis=1))     
# returns the largest element in each row

In [ ]:
print(b.mean(axis=0))         # returns the mean in each column

In [ ]:
a = np.array(['a','b','c'])

## Basic Math

No matter the number of dimensions in an array, simple arithmetic can be performed on an element-by-element basis.  
The operations will be applied to each element and the output will be an array of the same shape as the input array.

In [ ]:
a = np.array([2,2,3,4,4])
b = np.array([4,6,6,9,8])
c = a + b
c

In [ ]:
a = np.array([[[0, 1],[2, 3],[ 4,  5]],[[6, 7],[8, 9],[10, 11]]])   # three-dimensional array
print(a)

In [ ]:
b = np.array([[12, 13, 14, 15],[16, 17, 18, 19],[20, 21, 22, 23]])  # two-dimensional array
print(b)

In [ ]:
print(a+2)                                                 # three-dimensional result array

In [ ]:
print((b-10)/2)                                            # two-dimensional result array

In [ ]:
print(a**2)                                                # three-dimensional result array

In [ ]:
print(a**0.5)                                              # three-dimensional result array

When arrays are of the exact same shape element-by-element mathematical operations can be performed between them, producing an array of identical shape as a result.

In [ ]:
a = np.array([[0, 1, 22, 3],[4, 5, 66, 7]])           # two-dimensional array
b = np.array([[12, 13, 14, 15],[16, 17, 18, 19]])     # two-dimensional array

print("Addition")                                     # NumPy provides options in functional and mathematical notation
print(a+b)
print("Comparison")                       
print(a>b)
print(np.greater_equal(x, y))
print(np.less(a,b))

# Breakout

Use your combined knowledge of NumPy to create array `x` of shape (3,9) containing random integers between -10 and 10. Then create an array of booleans that determines whether each element is greater than 0. 

# Learning Objectives 

- Introduction to Arrays. Introduce, describe and create NumPy arrays.      
- Array Creation. Create and shape placeholder arrays.
- Array Basic Operations. Carry out basic operations on arrays.   